import * as THREE from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';

const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const defs=[
 {name:'雷咒师',role:'法师',icon:'⚡',color:0x58cfff,hp:760,atk:76,range:8.4,speed:7.1,skills:['雷链','霆狱','九霄天罚'],desc:'连锁闪电、范围雷狱与全场天罚'},
 {name:'玄甲卫',role:'坦克',icon:'🛡️',color:0xe2bd78,hp:1320,atk:48,range:2.2,speed:5.7,skills:['镇岳击','玄甲阵','山河震'],desc:'重甲控制、团队护盾和群体震飞'},
 {name:'夜行刃',role:'刺客',icon:'🗡️',color:0xc681ff,hp:790,atk:96,range:2.1,speed:8.2,skills:['影袭','无形步','瞬狱杀'],desc:'高速突进、隐身和残血斩杀'},
 {name:'星弦',role:'射手',icon:'🏹',color:0x72edbc,hp:720,atk:82,range:9.2,speed:7.4,skills:['穿云矢','逐星步','群星坠'],desc:'穿透箭、机动强化和持续箭雨'},
 {name:'青灯使',role:'辅助',icon:'🏮',color:0xa7ff8e,hp:870,atk:55,range:7.2,speed:6.8,skills:['引魂灯','回春渡','彼岸华光'],desc:'弹射法术、群体治疗和团队结界'},
 {name:'炎武尊',role:'战士',icon:'🔥',color:0xff7b53,hp:1040,atk:72,range:2.4,speed:6.6,skills:['焚拳','浴火身','炎神降世'],desc:'近战吸血、持续强化和狂暴变身'}
];
let scene,camera,renderer,clock,raycaster,ground,game=null,templates=[],animations=[],loaded=0,fpsFrames=0,fpsTime=0;
const loader=new GLTFLoader(), mixers=[], keys={}, joy={x:0,y:0,id:null};
window.addEventListener('error',e=>showError(e.message));window.addEventListener('unhandledrejection',e=>showError(e.reason?.message||String(e.reason)));
function showError(t){$('#error').style.display='block';$('#error').textContent='运行错误：'+t}

initRenderer();loadAssets();
function initRenderer(){scene=new THREE.Scene();scene.background=new THREE.Color(0x07121c);scene.fog=new THREE.FogExp2(0x132331,.012);camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,250);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;document.body.prepend(renderer.domElement);clock=new THREE.Clock();raycaster=new THREE.Raycaster();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function loadAssets(){for(let i=0;i<6;i++)loader.load(`./models/hero-${i}.glb`,g=>{g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});templates[i]=g.scene;animations[i]=g.animations;assetDone()},undefined,e=>{showError(`英雄${i+1}模型加载失败`);console.error(e)})}
function assetDone(){loaded++;$('#progress').style.width=(loaded/6*100)+'%';$('#loadText').textContent=`已唤醒 ${loaded}/6 位英雄`;if(loaded===6){setTimeout(()=>{$('#loading').classList.add('hidden');buildCards();$('#select').classList.remove('hidden')},250)}}
function buildCards(){const box=$('#cards');defs.forEach((d,i)=>{let b=document.createElement('button');b.className='card';b.innerHTML=`<div class="portrait" style="color:#${d.color.toString(16).padStart(6,'0')}">${d.icon}</div><small>${d.role}</small><strong>${d.name}</strong><p>${d.desc}</p><em>${d.skills.join(' · ')}</em>`;b.onclick=()=>start(i);box.appendChild(b)})}

function start(pick){$('#select').classList.add('hidden');$('#hud').classList.remove('hidden');buildWorld();const rest=[0,1,2,3,4,5].filter(i=>i!==pick),order=[pick,...rest];game={time:0,last:performance.now(),heroes:[],minions:[],shots:[],zones:[],structures:[],effects:[],blueKills:0,redKills:0,wave:1,over:false,player:null,utility:{recall:0,heal:0,flash:0}};order.slice(0,3).forEach((id,i)=>spawnHero(id,0,new THREE.Vector3(-48+i*1.8,0,-5+i*5),i===0));order.slice(3).forEach((id,i)=>spawnHero(id,1,new THREE.Vector3(48-i*1.8,0,-5+i*5)));spawnStructures();buildTeamStrip();feed('战斗开始：摧毁敌方诸界核心！',0xffdc80);clock.start();requestAnimationFrame(loop)}
function buildTeamStrip(){let box=$('#teamStrip');box.innerHTML='';for(const h of game.heroes){let face=document.createElement('div');face.className='team-face'+(h.team?' enemy':'');face.textContent=h.def.icon;face.title=`${h.team?'赤渊':'苍穹'} · ${h.def.name}`;box.appendChild(face)}}
function buildWorld(){scene.clear();mixers.length=0;scene.background=new THREE.Color(0x0a1923);scene.fog=new THREE.FogExp2(0x132a33,.012);scene.add(new THREE.HemisphereLight(0xa9d5ff,0x263012,1.65));let sun=new THREE.DirectionalLight(0xffe2b6,2.2);sun.position.set(-25,48,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;scene.add(sun);
 const tex=new THREE.CanvasTexture(makeGroundTexture());tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(14,7);ground=new THREE.Mesh(new THREE.PlaneGeometry(130,66),new THREE.MeshStandardMaterial({map:tex,roughness:.95,metalness:.02}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);let lane=new THREE.Mesh(new THREE.PlaneGeometry(120,16),new THREE.MeshStandardMaterial({color:0x4c5360,roughness:1}));lane.rotation.x=-Math.PI/2;lane.position.y=.015;lane.receiveShadow=true;scene.add(lane);for(let x=-52;x<=52;x+=8){let slab=new THREE.Mesh(new THREE.BoxGeometry(5.6,.12,11),new THREE.MeshStandardMaterial({color:x%16?0x4a5159:0x59606a,roughness:1}));slab.position.set(x,.08,0);slab.receiveShadow=true;scene.add(slab)}
 for(let i=0;i<42;i++){let side=i%2?1:-1,z=side*(11+Math.random()*18),x=-58+Math.random()*116;makeTree(x,z,rand(.7,1.45))}for(let i=0;i<24;i++)makeBush(-58+Math.random()*116,(i%2?1:-1)*rand(9,25),rand(.7,1.4));for(let i=0;i<20;i++)makeRock(-58+Math.random()*116,(i%2?1:-1)*rand(10,27),rand(.65,1.45));for(let i=0;i<18;i++)makeCrystal(-58+Math.random()*116,(i%2?1:-1)*rand(10,25),i%2?0x46cfff:0xff5577);makeRiver();}
function makeGroundTexture(){let c=document.createElement('canvas');c.width=c.height=256;let x=c.getContext('2d');x.fillStyle='#24402f';x.fillRect(0,0,256,256);for(let i=0;i<2500;i++){x.fillStyle=Math.random()>.5?'#31523a':'#1b3528';x.fillRect(Math.random()*256,Math.random()*256,1,rand(1,4))}return c}
function makeTree(x,z,s){let g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.25,.4,2.5,7),new THREE.MeshStandardMaterial({color:0x463222})),top=new THREE.Mesh(new THREE.ConeGeometry(1.4,3.4,8),new THREE.MeshStandardMaterial({color:0x173b2a,roughness:1}));tr.position.y=1.25;top.position.y=3.4;g.add(tr,top);g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
function makeBush(x,z,s){let g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x1e6a3d,roughness:1});for(let i=0;i<7;i++){let b=new THREE.Mesh(new THREE.ConeGeometry(.42,.95,6),mat);b.position.set(rand(-.7,.7),.45,rand(-.55,.55));b.rotation.z=rand(-.35,.35);g.add(b)}g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
function makeRock(x,z,s){let m=new THREE.Mesh(new THREE.DodecahedronGeometry(1,0),new THREE.MeshStandardMaterial({color:0x566267,roughness:.92}));m.position.set(x,.65*s,z);m.scale.set(s*1.25,s*.7,s);m.rotation.set(rand(-.2,.2),rand(0,6.2),rand(-.15,.15));m.castShadow=m.receiveShadow=true;scene.add(m)}
function makeCrystal(x,z,c){let m=new THREE.Mesh(new THREE.OctahedronGeometry(.45,0),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.4,roughness:.25}));m.position.set(x,.55,z);scene.add(m)}
function makeRiver(){let r=new THREE.Mesh(new THREE.PlaneGeometry(7,66),new THREE.MeshStandardMaterial({color:0x155b70,transparent:true,opacity:.72,roughness:.2,metalness:.25}));r.rotation.x=-Math.PI/2;r.position.y=.03;scene.add(r)}

function spawnHero(id,team,pos,player=false){let root=new THREE.Group(),model=templates[id].clone(true);model.scale.setScalar(3.15);model.position.y=.03;root.add(model);root.position.copy(pos);scene.add(root);tintTeam(model,team);addHeroGear(root,id,team,player);let mixer=new THREE.AnimationMixer(model),clips={};for(const a of animations[id])clips[a.name]=mixer.clipAction(a);clips.idle?.play();mixers.push(mixer);let h={kind:'hero',id,def:defs[id],team,root,model,mixer,clips,anim:'idle',pos:root.position,spawn:pos.clone(),player,hp:defs[id].hp,maxHp:defs[id].hp,mana:100,atk:defs[id].atk,range:defs[id].range,speed:defs[id].speed,dead:false,respawn:0,cd:[0,0,0,0],shield:0,buff:0,invis:0,kills:0,deaths:0,level:1,xp:0,lastDir:new THREE.Vector3(team? -1:1,0,0)};makeBar(h);game.heroes.push(h);if(player)game.player=h;return h}
function tintTeam(model,team){model.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.emissive=new THREE.Color(team?0x210008:0x001728);o.material.emissiveIntensity=.35}})}
function addHeroGear(root,id,team,player=false){const mat=new THREE.MeshStandardMaterial({color:defs[id].color,metalness:.55,roughness:.35,emissive:defs[id].color,emissiveIntensity:.22});let weapon;if(id===0){weapon=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,2.4,8),mat);weapon.rotation.z=.25;weapon.position.set(.86,1.18,.18);let orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.26),mat);orb.position.y=1.25;weapon.add(orb);let halo=new THREE.Mesh(new THREE.TorusGeometry(.42,.055,8,24),mat);halo.rotation.x=Math.PI/2;halo.position.set(0,2.18,0);root.add(halo)}else if(id===1){weapon=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.35,.2),mat);weapon.position.set(.95,1,.18);for(const s of[-1,1]){let pad=new THREE.Mesh(new THREE.DodecahedronGeometry(.28),mat);pad.position.set(s*.72,1.48,0);root.add(pad)}}else if(id===2){weapon=new THREE.Group();for(const s of[-1,1]){let b=new THREE.Mesh(new THREE.BoxGeometry(.12,1.45,.12),mat);b.position.set(s*.72,1.05,.25);b.rotation.z=s*.42;weapon.add(b)}}else if(id===3){weapon=new THREE.Mesh(new THREE.TorusGeometry(.74,.075,7,22,Math.PI*1.48),mat);weapon.rotation.y=Math.PI/2;weapon.position.set(.88,1.18,.18);let quiver=new THREE.Mesh(new THREE.CylinderGeometry(.16,.2,1.15,8),mat);quiver.rotation.z=.24;quiver.position.set(-.6,1.22,-.28);root.add(quiver)}else if(id===4){weapon=new THREE.Mesh(new THREE.CylinderGeometry(.22,.29,.62,8),mat);weapon.position.set(.78,1.25,.35);let glow=new THREE.PointLight(defs[id].color,1.8,5);weapon.add(glow);let crown=new THREE.Mesh(new THREE.ConeGeometry(.36,.45,6),mat);crown.position.set(0,2.12,0);root.add(crown)}else{weapon=new THREE.Group();for(const s of[-1,1]){let f=new THREE.Mesh(new THREE.IcosahedronGeometry(.3),mat);f.position.set(s*.72,1.05,.4);weapon.add(f)}}root.add(weapon);let ring=new THREE.Mesh(new THREE.TorusGeometry(player?1.15:.92,player?.065:.045,8,36),new THREE.MeshBasicMaterial({color:player?0xffe46a:(team?0xff4265:0x3fcfff)}));ring.rotation.x=Math.PI/2;ring.position.y=.05;root.add(ring)}
function makeBar(e){let c=document.createElement('canvas');c.width=192;c.height=48;let tex=new THREE.CanvasTexture(c),spr=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false}));spr.scale.set(e.kind==='hero'?3.25:2.15,e.kind==='hero'?.82:.54,1);spr.position.y=e.kind==='hero'?3.15:1.35;e.root.add(spr);e.bar={c,ctx:c.getContext('2d'),tex,spr};updateBar(e)}
function updateBar(e){if(!e.bar)return;let x=e.bar.ctx;x.clearRect(0,0,192,48);if(e.kind==='hero'){x.font='bold 15px sans-serif';x.textAlign='center';x.fillStyle='#fff';x.shadowColor='#000';x.shadowBlur=4;x.fillText(`Lv.${e.level||1}  ${e.def?.name||''}`,96,15);x.shadowBlur=0}x.fillStyle='#160711';x.fillRect(10,22,172,14);x.fillStyle=e.team?'#ff5473':'#46d2ff';x.fillRect(10,22,172*clamp(e.hp/e.maxHp,0,1),14);x.strokeStyle='#fff9';x.lineWidth=2;x.strokeRect(10,22,172,14);e.bar.tex.needsUpdate=true}

function spawnStructures(){for(const team of[0,1]){let sx=team?55:-55,tx=team?35:-35;game.structures.push(makeStructure(team,'core',sx,0),makeStructure(team,'tower',tx,0))}}
function makeStructure(team,kind,x,z){let root=new THREE.Group(),c=team?0xff365e:0x31caff,base=new THREE.Mesh(new THREE.CylinderGeometry(kind==='core'?2.5:1.7,kind==='core'?3.2:2.2,kind==='core'?1.2:1.0,8),new THREE.MeshStandardMaterial({color:team?0x4d1724:0x12394e,metalness:.4,roughness:.55}));base.position.y=.6;base.castShadow=true;root.add(base);if(kind==='tower'){for(let i=0;i<3;i++){let p=new THREE.Mesh(new THREE.BoxGeometry(.5,3.7,.5),new THREE.MeshStandardMaterial({color:0x5e6872,metalness:.5}));p.position.set(Math.cos(i*2.1)*.8,2.3,Math.sin(i*2.1)*.8);root.add(p)}let gem=new THREE.Mesh(new THREE.OctahedronGeometry(.75),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.8}));gem.position.y=4.2;root.add(gem)}else{let gem=new THREE.Mesh(new THREE.IcosahedronGeometry(1.55,1),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.5,transparent:true,opacity:.92}));gem.position.y=2.6;root.add(gem);root.userData.gem=gem}root.position.set(x,0,z);scene.add(root);let e={kind,team,root,pos:root.position,hp:kind==='core'?3000:1650,maxHp:kind==='core'?3000:1650,range:kind==='core'?11:10,atk:kind==='core'?115:90,cd:0,dead:false};makeBar(e);e.bar.spr.position.y=kind==='core'?4.7:5.3;return e}
function spawnWave(){for(const team of[0,1])for(let i=0;i<4;i++)spawnMinion(team,i)}
function spawnMinion(team,i){let root=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.32,.55,3,7),new THREE.MeshStandardMaterial({color:team?0xa32642:0x18799f,roughness:.7,metalness:.2})),helm=new THREE.Mesh(new THREE.ConeGeometry(.38,.5,7),new THREE.MeshStandardMaterial({color:team?0xff6a80:0x5bdcff,metalness:.55}));body.position.y=.65;helm.position.y=1.35;root.add(body,helm);root.position.set(team?51:-51,0,(i-1.5)*.8);scene.add(root);let e={kind:'minion',team,root,pos:root.position,hp:250,maxHp:250,atk:i===3?30:24,range:i===3?5.2:1.25,speed:3.2,cd:0,dead:false,lastDir:new THREE.Vector3(team?-1:1,0,0)};makeBar(e);game.minions.push(e)}

const all=()=>[...game.heroes,...game.minions,...game.structures], enemies=o=>all().filter(e=>e.team!==o.team&&!e.dead&&e.hp>0&&!(e.kind==='core'&&game.structures.some(s=>s.team===e.team&&s.kind==='tower'&&!s.dead))), friends=o=>game.heroes.filter(e=>e.team===o.team&&!e.dead);
function nearest(o,list=enemies(o)){let t=null,d=1e9;for(const e of list){let q=o.pos.distanceTo(e.pos);if(q<d){d=q;t=e}}return[t,d]}
function face(o,t){if(!t)return;let dx=t.pos.x-o.pos.x,dz=t.pos.z-o.pos.z;o.root.rotation.y=Math.atan2(dx,dz);o.lastDir.set(dx,0,dz).normalize()}
function setAnim(h,n,once=false){if(h.anim===n)return;let next=h.clips[n]||h.clips.idle;if(!next)return;let cur=h.clips[h.anim];cur?.fadeOut(.12);next.reset().fadeIn(.12);next.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);next.clampWhenFinished=once;next.play();h.anim=n;if(once)setTimeout(()=>{if(!h.dead)setAnim(h,'idle')},480)}
function hurt(src,t,n){if(!t||t.dead)return;n*=t.shield>0?.58:1;t.hp-=n;updateBar(t);floatText(t.pos,'-'+Math.round(n),0xff6680);pulse(t.pos,src?.team?0xff405f:0x3fd8ff,.8);if(t.hp<=0)kill(src,t)}
function heal(t,n){t.hp=Math.min(t.maxHp,t.hp+n);updateBar(t);floatText(t.pos,'+'+Math.round(n),0x65ff96);pulse(t.pos,0x59ff91,.65)}
function kill(src,t){t.hp=0;t.dead=true;updateBar(t);if(t.kind==='hero'){t.deaths++;t.respawn=7;t.root.visible=false;setAnim(t,'die',true);if(src?.kind==='hero'){src.kills++;src.xp+=100;src.team?game.redKills++:game.blueKills++;feed(`${src.def.name} 击败 ${t.def.name}`,src.team?0xff6883:0x64ddff);levelCheck(src)}}else{t.root.visible=false;if(t.kind==='tower')feed(`${t.team?'赤渊':'苍穹'}防御塔已经倒塌！`,0xffd36b);if(t.kind==='core')finish(src?.team===0)}}
function levelCheck(h){let need=h.level*120;if(h.xp>=need&&h.level<12){h.xp-=need;h.level++;h.maxHp+=70;h.hp+=70;h.atk+=8;updateBar(h);floatText(h.pos,'升级！',0xffdb65)}}
function basic(h){if(!h||h.dead||h.cd[3]>0)return;let[t,d]=nearest(h);if(!t||d>h.range+1)return;h.cd[3]=.72;face(h,t);setAnim(h,h.range>3?'holding-right-shoot':'attack-melee-right',true);if(h.range>3)projectile(h,t,h.atk,h.def.color,18);else setTimeout(()=>{if(!t.dead&&h.pos.distanceTo(t.pos)<h.range+1.4)hurt(h,t,h.atk)},220)}
function projectile(src,t,dmg,color,speed=20){let m=new THREE.Mesh(new THREE.SphereGeometry(.17,8,6),new THREE.MeshBasicMaterial({color}));m.position.copy(src.pos).add(new THREE.Vector3(0,1.2,0));scene.add(m);game.shots.push({mesh:m,pos:m.position,target:t,src,dmg,speed})}
function cast(h,s){if(!h||h.dead||h.cd[s]>0||h.mana<(s===2?40:22))return;let[t,d]=nearest(h);h.mana-=s===2?40:22;h.cd[s]=[5,9,20][s];let id=h.id;setAnim(h,id===3?'holding-both-shoot':'attack-melee-left',true);
 if(id===0){if(s===0&&t)enemies(h).sort((a,b)=>a.pos.distanceTo(t.pos)-b.pos.distanceTo(t.pos)).slice(0,3).forEach((e,i)=>{lightning(h.pos,e.pos,0x6fcfff);hurt(h,e,130-i*25)});if(s===1&&t)zone(t.pos,3.8,3,h.team,38,0x4abfff);if(s===2)enemies(h).filter(e=>e.kind==='hero').forEach(e=>{lightning(new THREE.Vector3(e.pos.x,12,e.pos.z),e.pos,0xb6e7ff);hurt(h,e,220)})}
 if(id===1){if(s===0&&t&&d<4){hurt(h,t,170);ring(t.pos,0xe6c078,2.4)}if(s===1)friends(h).forEach(a=>{if(a.pos.distanceTo(h.pos)<8)a.shield=5});if(s===2){ring(h.pos,0xffd37a,7);enemies(h).filter(e=>e.pos.distanceTo(h.pos)<7).forEach(e=>hurt(h,e,210))}}
 if(id===2){if(s===0&&t){let v=t.pos.clone().sub(h.pos).setY(0),l=Math.min(6,Math.max(0,v.length()-1));v.normalize();h.pos.addScaledVector(v,l);face(h,t);hurt(h,t,155);trail(h.pos,0xca75ff)}if(s===1){h.invis=3.5;h.buff=3.5;h._opaque=false;h.root.traverse(o=>{if(o.material){o.material.transparent=true;o.material.opacity=.28}})}if(s===2&&t){trail(t.pos,0xe8b2ff);hurt(h,t,t.hp/t.maxHp<.4?430:240)}}
 if(id===3){if(s===0&&t)projectile(h,t,190,0x83ffce,28);if(s===1){h.buff=5;trail(h.pos,0x70ffd0)}if(s===2&&t)zone(t.pos,4.7,4.2,h.team,48,0x72efc2)}
 if(id===4){if(s===0&&t){projectile(h,t,105,0xa6ff8d,20);let q=nearest(t,enemies(h).filter(e=>e!==t))[0];if(q)projectile(h,q,75,0x7cffb2,20)}if(s===1)friends(h).filter(a=>a.pos.distanceTo(h.pos)<10).forEach(a=>heal(a,190));if(s===2){friends(h).forEach(a=>{a.shield=7;heal(a,100)});ring(h.pos,0xaaff9a,9)}}
 if(id===5){if(s===0&&t&&d<4){hurt(h,t,180);heal(h,65);burst(t.pos,0xff6b40)}if(s===1){h.buff=7;h.shield=3;trail(h.pos,0xff7c48)}if(s===2){h.buff=10;h.atk+=32;setTimeout(()=>h.atk-=32,10000);ring(h.pos,0xff492f,6)}}
}
function zone(pos,r,life,team,dmg,color){let mesh=new THREE.Mesh(new THREE.CircleGeometry(r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(pos);mesh.position.y=.08;scene.add(mesh);game.zones.push({mesh,pos:mesh.position,r,life,team,dmg,tick:0})}
function ring(pos,color,r){let m=new THREE.Mesh(new THREE.RingGeometry(r*.82,r,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.12;scene.add(m);game.effects.push({mesh:m,life:.55,grow:1.5})}
function pulse(pos,color,r){ring(pos,color,r)}function trail(pos,color){for(let i=0;i<8;i++){let m=new THREE.Mesh(new THREE.SphereGeometry(.12),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(pos).add(new THREE.Vector3(rand(-1.2,1.2),rand(.1,1.8),rand(-1.2,1.2)));scene.add(m);game.effects.push({mesh:m,life:.7,vy:1})}}
function burst(pos,color){for(let i=0;i<14;i++)trail(pos,color)}
function lightning(a,b,color){let pts=[a.clone().add(new THREE.Vector3(0,1.1,0))];for(let i=1;i<5;i++)pts.push(a.clone().lerp(b,i/5).add(new THREE.Vector3(rand(-.45,.45),rand(.5,1.8),rand(-.45,.45))));pts.push(b.clone().add(new THREE.Vector3(0,1,0)));let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity:1}));scene.add(line);game.effects.push({mesh:line,life:.25})}

function movePlayer(h,dt){let x=(keys.d?1:0)-(keys.a?1:0)+joy.x,z=(keys.s?1:0)-(keys.w?1:0)+joy.y,l=Math.hypot(x,z);if(l>.12){x/=l;z/=l;let sp=h.speed*(h.buff>0?1.3:1);h.pos.x=clamp(h.pos.x+x*sp*dt,-60,60);h.pos.z=clamp(h.pos.z+z*sp*dt,-29,29);h.root.rotation.y=Math.atan2(x,z);h.lastDir.set(x,0,z);setAnim(h,'sprint')}else setAnim(h,'idle')}
function useUtility(type){if(!game||game.over||!game.player||game.player.dead||game.utility[type]>0)return;let p=game.player;if(type==='recall'){game.utility.recall=18;ring(p.pos,0x55cfff,3.3);trail(p.pos,0x7de6ff);p.pos.copy(p.spawn);p.hp=p.maxHp;p.mana=100;updateBar(p);feed(`${p.def.name} 已返回泉水`,0x7fe6ff)}else if(type==='heal'){game.utility.heal=14;heal(p,p.maxHp*.3);friends(p).filter(a=>a!==p&&a.pos.distanceTo(p.pos)<7).forEach(a=>heal(a,a.maxHp*.14));ring(p.pos,0x72ff91,4)}else if(type==='flash'){game.utility.flash=12;let from=p.pos.clone(),dir=p.lastDir.clone();if(dir.lengthSq()<.01)dir.set(1,0,0);p.pos.x=clamp(p.pos.x+dir.x*6.5,-60,60);p.pos.z=clamp(p.pos.z+dir.z*6.5,-29,29);trail(from,0xffd55c);trail(p.pos,0xffe58a)}}
function aiHero(h,dt){let[t,d]=nearest(h);if(h.hp/h.maxHp<.27){let v=h.spawn.clone().sub(h.pos).setY(0);if(v.length()>1){v.normalize();h.pos.addScaledVector(v,h.speed*dt);h.root.rotation.y=Math.atan2(v.x,v.z);setAnim(h,'sprint')}if(d<5)cast(h,1);return}if(!t)return;if(d>h.range*.78){let v=t.pos.clone().sub(h.pos).setY(0).normalize();h.pos.addScaledVector(v,h.speed*dt*.74);h.root.rotation.y=Math.atan2(v.x,v.z);setAnim(h,'walk')}else{setAnim(h,'idle');basic(h)}if(d<h.range*1.35&&Math.random()<dt*.38)cast(h,Math.random()<.16?2:(Math.random()<.55?0:1))}
function update(dt){game.time+=dt;game.wave-=dt;for(const k in game.utility)game.utility[k]=Math.max(0,game.utility[k]-dt);if(game.wave<=0){spawnWave();game.wave=12}for(const h of game.heroes){h.mixer.update(dt);for(let i=0;i<4;i++)h.cd[i]=Math.max(0,h.cd[i]-dt);h.shield=Math.max(0,h.shield-dt);h.buff=Math.max(0,h.buff-dt);h.invis=Math.max(0,h.invis-dt);h.mana=Math.min(100,h.mana+7*dt);if(h.invis<=0&&h.model.children.length&&h.root.visible&&!h._opaque){h.root.traverse(o=>{if(o.material){o.material.opacity=1;o.material.transparent=false}});h._opaque=true}if(h.dead){h.respawn-=dt;if(h.respawn<=0){h.dead=false;h.hp=h.maxHp;h.mana=100;h.pos.copy(h.spawn);h.root.visible=true;h._opaque=false;setAnim(h,'idle');updateBar(h)}continue}h.player?movePlayer(h,dt):aiHero(h,dt)}
 for(const m of game.minions){if(m.dead)continue;m.cd-=dt;let[t,d]=nearest(m);if(t&&d<m.range){if(m.cd<=0){m.cd=1.05;m.range>2?minionShot(m,t):hurt(m,t,m.atk)}}else{m.pos.x+=(m.team?-1:1)*m.speed*dt;m.root.rotation.y=m.team?-Math.PI/2:Math.PI/2}}
 for(const s of game.structures){if(s.dead)continue;s.cd-=dt;if(s.root.userData.gem)s.root.userData.gem.rotation.y+=dt;let[t,d]=nearest(s,enemies(s).filter(e=>e.kind!=='tower'&&e.kind!=='core'));if(t&&d<s.range&&s.cd<=0){s.cd=1;projectile(s,t,s.atk,s.team?0xff4868:0x42d6ff,20)}}
 for(const q of game.shots){if(q.target.dead){q.dead=true;continue}let v=q.target.pos.clone().add(new THREE.Vector3(0,.8,0)).sub(q.pos),d=v.length();if(d<.45){hurt(q.src,q.target,q.dmg);q.dead=true;scene.remove(q.mesh)}else q.pos.addScaledVector(v.normalize(),q.speed*dt)}game.shots=game.shots.filter(q=>!q.dead);
 for(const z of game.zones){z.life-=dt;z.tick-=dt;z.mesh.material.opacity=.16+.09*Math.sin(game.time*7);if(z.tick<=0){z.tick=.45;all().filter(e=>e.team!==z.team&&!e.dead&&e.pos.distanceTo(z.pos)<z.r).forEach(e=>hurt(null,e,z.dmg))}if(z.life<=0)scene.remove(z.mesh)}game.zones=game.zones.filter(z=>z.life>0);
 for(const e of game.effects){e.life-=dt;if(e.vy)e.mesh.position.y+=e.vy*dt;if(e.grow)e.mesh.scale.multiplyScalar(1+e.grow*dt);if(e.mesh.material)e.mesh.material.opacity=clamp(e.life*2,0,1);if(e.life<=0)scene.remove(e.mesh)}game.effects=game.effects.filter(e=>e.life>0);game.minions=game.minions.filter(m=>{if(m.dead||Math.abs(m.pos.x)>62){scene.remove(m.root);return false}return true});followCamera(dt);updateHUD()}
function minionShot(m,t){projectile(m,t,m.atk,m.team?0xff5874:0x50d6ff,15)}
function followCamera(dt){let p=game.player,desired=p.pos.clone().add(new THREE.Vector3(-8.2,14.5,12.6));camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(p.pos.x+2.2,p.pos.y+.55,p.pos.z)}
function updateHUD(){let p=game.player;$('#heroName').textContent=p.def.name+' · '+p.def.role;$('#level').textContent='  Lv.'+p.level;$('#hp').style.width=100*p.hp/p.maxHp+'%';$('#mp').style.width=p.mana+'%';$('#xp').style.width=100*p.xp/(p.level*120)+'%';$('#bk').textContent=game.blueKills;$('#rk').textContent=game.redKills;let s=Math.floor(game.time);$('#time').textContent=String(s/60|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0');p.def.skills.forEach((n,i)=>$('#sk'+i).textContent=n);document.querySelectorAll('.skill').forEach(b=>{let s=b.dataset.s,cd=s==='a'?p.cd[3]:p.cd[+s],o=b.querySelector('.cd');o.style.display=cd>0?'flex':'none';o.textContent=cd>0?cd.toFixed(cd<3?1:0):''});document.querySelectorAll('.util').forEach(b=>{let cd=game.utility[b.dataset.u],o=b.querySelector('.cd');o.style.display=cd>0?'flex':'none';o.textContent=cd>0?Math.ceil(cd):''});drawMap()}
function drawMap(){let c=$('#map'),x=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=c.clientHeight*2;x.clearRect(0,0,w,h);x.fillStyle='#163726';x.fillRect(0,0,w,h);x.fillStyle='#5e6267';x.fillRect(0,h*.39,w,h*.22);x.fillStyle='#1c6980';x.fillRect(w*.475,0,w*.05,h);for(const e of all()){if(e.dead)continue;x.fillStyle=e.team?'#ff536f':'#4bd8ff';let px=(e.pos.x+65)/130*w,pz=(e.pos.z+33)/66*h,r=e.kind==='hero'?5:e.kind==='core'?6:3;x.beginPath();x.arc(px,pz,r,0,7);x.fill()}}
function floatText(pos,text,color){let v=pos.clone().add(new THREE.Vector3(0,2.5,0)).project(camera),d=document.createElement('div');d.className='damage';d.style.color='#'+color.toString(16).padStart(6,'0');d.style.left=(v.x*.5+.5)*innerWidth+'px';d.style.top=(-v.y*.5+.5)*innerHeight+'px';d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),760)}
function feed(text,color=0xffffff){let d=document.createElement('div');d.className='feed';d.style.color='#'+color.toString(16).padStart(6,'0');d.textContent=text;$('#feed').prepend(d);setTimeout(()=>d.remove(),5200)}
function finish(blue){if(game.over)return;game.over=true;$('#hud').classList.add('hidden');$('#end').classList.remove('hidden');$('#result').textContent=blue?'赤晶破碎 · 苍穹胜利':'苍穹陷落 · 赤渊胜利';$('#result').style.color=blue?'#55d8ff':'#ff5d7b';let p=game.player;$('#stats').textContent=`${p.def.name}　击败 ${p.kills}　阵亡 ${p.deaths}　等级 ${p.level}`}
function loop(){if(!game||game.over)return;let dt=Math.min(.05,clock.getDelta());fpsFrames++;fpsTime+=dt;if(fpsTime>=.5){$('#fps').textContent=Math.round(fpsFrames/fpsTime);fpsFrames=0;fpsTime=0}update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}

addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(!game)return;let p=game.player,k=e.key.toLowerCase();if(k==='j')basic(p);if(k==='k')cast(p,0);if(k==='l')cast(p,1);if(k==='u')cast(p,2);if(k==='r')useUtility('recall');if(k==='f')useUtility('heal');if(k==='g')useUtility('flash')});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const j=$('#joy'),kn=$('#knob');function moveJoy(e){let t=[...e.changedTouches].find(q=>joy.id===null||q.identifier===joy.id);if(!t)return;if(joy.id===null)joy.id=t.identifier;let r=j.getBoundingClientRect(),dx=t.clientX-r.left-r.width/2,dy=t.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),m=r.width*.35;if(l>m){dx*=m/l;dy*=m/l}joy.x=dx/m;joy.y=dy/m;kn.style.transform=`translate(${dx}px,${dy}px)`}j.addEventListener('touchstart',e=>{e.preventDefault();moveJoy(e)},{passive:false});j.addEventListener('touchmove',e=>{e.preventDefault();moveJoy(e)},{passive:false});j.addEventListener('touchend',e=>{if([...e.changedTouches].some(t=>t.identifier===joy.id)){joy.x=joy.y=0;joy.id=null;kn.style.transform=''}},{passive:false});document.querySelectorAll('.skill').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();if(!game)return;b.dataset.s==='a'?basic(game.player):cast(game.player,+b.dataset.s)}));
document.querySelectorAll('.util').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();useUtility(b.dataset.u)}));
function rand(a,b){return a+Math.random()*(b-a)}
